#!/usr/bin/env bash
# Tool for getting paths from Open Verification Language install.
# Copyright (C) 2010-2011 Ole Henrik Jahren <olehenja@alumni.ntnu.no>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Reminder where to look for programs if any are missing:
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/common/bin/lin64
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/PlanAhead/bin
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/ISE/bin/lin64
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/ISE/sysgen/util
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/EDK/bin/lin64

prog="`basename "$0"`"

die()
{
	echo "$@" >&2
	exit 1
}

usage()
{
	cat >&2 << EOF
usage: $prog <language> [options]

Legal languages are:
  verilog

Options:
  --lib
  --include
EOF
}

if test -z "$OVL_PATH" ; then
	die "$prog: error: \$OVL_PATH environment variable is not set"
fi

if test ! -d "$OVL_PATH" ; then
	die "$prog: error: could not find directory '$OVL_PATH'"
fi

if test "$#" -lt 1 ; then
	usage
	echo "" >&2
	die "$prog: error: you must atleast specify a language"
fi

language="$1"
shift

output=""
while test $# -gt 0 ; do
	arg="$1"
	tmp=""
	shift
	case "$arg" in
	--lib)
		tmp="-y$OVL_PATH"
		;;
	--include)
		tmp="-I$OVL_PATH"
		;;
	*)
		die "$prog: error: unknown option '$arg'"
		;;
	esac
	if test -n "$output" ; then
		output="$output $tmp"
	else
		output="$tmp"
	fi
done

if test -n "$output" ; then
	echo "$output"
fi
