#!/usr/bin/env bash
# Tool for getting paths from Open Verification Language install.
# Copyright (C) 2010-2011 Ole Henrik Jahren <olehenja@alumni.ntnu.no>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Reminder where to look for programs if any are missing:
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/common/bin/lin64
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/PlanAhead/bin
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/ISE/bin/lin64
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/ISE/sysgen/util
# $XI_WRAPPER_PREFIX/$XI_WRAPPER_VERSION/ISE_DS/EDK/bin/lin64

prog="`basename "$0"`"

die()
{
	echo "$@" >&2
	exit 1
}

usage()
{
	cat >&2 << EOF
usage: $prog [options] [--]

      --format=fmt              Format of command line. Default is iverilog.
  -h, --help                    Show this help message.
      --include                 Output include directories.
      --lib                     Output library directories.
EOF
}

if test -z "$OVL_PATH" ; then
	die "$prog: error: \$OVL_PATH environment variable is not set"
fi

if test ! -d "$OVL_PATH" ; then
	die "$prog: error: could not find directory '$OVL_PATH'"
fi

opt_lib=0
opt_include=0
opt_format="iverilog"

while [ $# -gt 0 ] ; do
	case "$1" in
	--help|-h)
		usage
		exit 0
		;;
	--format=*)
		opt_format=${1:9}
		;;
	--lib)
		opt_lib=1
		;;
	--include)
		opt_include=1
		;;
	--)
		shift
		break
		;;
	-*)
		die "$prog: error: unknown option '$1'"
		;;
	*)
		break
		;;
	esac
	shift
done

case "$opt_format" in
isim)
	libopt="-sourcelibdir "
	extopt="-sourcelibext .vlib"
	includeopt="-include "
	;;
iverilog)
	libopt="-y"
	extopt="-Y.vlib"
	includeopt="-I"
	;;
verilator)
	libopt="-y "
	extopt="+libext+.vlib"
	includeopt="+incdir+"
	;;
*)
	die "$prog: error: illegal format '$opt_format'"
	;;
esac

output=""
if test $opt_lib -eq 1 ; then
	output="$extopt $libopt$OVL_PATH"
fi
if test $opt_include -eq 1 ; then
	tmp="$includeopt$OVL_PATH"
	if test -n "$output" ; then
		output="$output $tmp"
	else
		output="$tmp"
	fi
fi

if test -n "$output" ; then
	echo "$output"
fi
